## NumPy Basics

NumPy's main object is the homogeneous multi-dimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy, dimensions are called axes.

For example, the coordinates of a point in a 3-dimensional space `[1, 2, 1]` has one axis. That axis has 3 elements in it, so we say it has a length of 3. 

NumPy's array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the standard Python library class `array.array`, which only handles 1-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

- `ndarray.ndim`: the number of axes (dimensions) of the array
- `ndarray.shape`: the dimensions of the array
    - This is a tuple of integers indicating the size of the array in each dimension. For a matrix with `n` rows and `m` columns, the `shape` will be `(n, m)`. The length of the `shape` tuple is therefore the number of axes, `ndim`  
- `ndarray.size`: the total number of elements of the array
    - This is equal to the product of the elements of the `shape`, `n x m`
- `ndarray.dtype`: an object describing the type of elements in the array
    - One can create or specify `dtype`s using standard Python types. Additionally, NumPy provides types of its own, e.g., `numpy.int32`, `numpy.int16`, `numpy.float64`

### Example

In [176]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype

dtype('int64')

In [5]:
a.size

15

In [6]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.ndim

1

In [11]:
b.shape

(3,)

### Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [12]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [71]:
b = np.array([1.2, 3.5, 5.1, 6])
b.dtype

dtype('float64')

In [70]:
print(b)

[1.2 3.5 5.1 6. ]


A frequent error consists in calling an array with multiple arguments rather than providing a single sequence as an argument.

In [15]:
a = np.array(1,2,3,4) # wrong

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [17]:
a = np.array([1, 2, 3, 4]) # right
a

array([1, 2, 3, 4])

`array` transforms sequences of sequences into 2-dimensional arrays, sequences of sequences of sequences into 3-dimensional arrays, and so on.

In [18]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [19]:
b.dtype

dtype('float64')

In [20]:
b.ndim

2

The type of the array can also be explicitly specified at creation time:

In [21]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the `dtype` of the created array is `float64`.

In [177]:
c = np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [178]:
c.shape

(3, 4)

In [23]:
c.dtype

dtype('float64')

In [179]:
d = np.ones((2,3,4), dtype=np.int16) # dtype can also be specified
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [180]:
d.shape

(2, 3, 4)

In [26]:
d.ndim

3

In [181]:
f = np.empty((2,3), dtype=np.float16) # uninitialized
f

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [182]:
f.shape

(2, 3)

To create sequences of numbers, NumPy provides the `arange` function, which is analogous to the Python built-in `range`, but returns an array.

In [31]:
e = np.arange(10, 40, 5) # analogous to range(10, 40, 5)
e

array([10, 15, 20, 25, 30, 35])

In [32]:
np.arange(0, 3, 0.3) # accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want, instead of the step:

In [33]:
np.linspace(0, 2, 9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [35]:
from numpy import pi
x = np.linspace(0, 2*pi, 50) # useful to evaluate function at lots of points
x

array([0.        , 0.12822827, 0.25645654, 0.38468481, 0.51291309,
       0.64114136, 0.76936963, 0.8975979 , 1.02582617, 1.15405444,
       1.28228272, 1.41051099, 1.53873926, 1.66696753, 1.7951958 ,
       1.92342407, 2.05165235, 2.17988062, 2.30810889, 2.43633716,
       2.56456543, 2.6927937 , 2.82102197, 2.94925025, 3.07747852,
       3.20570679, 3.33393506, 3.46216333, 3.5903916 , 3.71861988,
       3.84684815, 3.97507642, 4.10330469, 4.23153296, 4.35976123,
       4.48798951, 4.61621778, 4.74444605, 4.87267432, 5.00090259,
       5.12913086, 5.25735913, 5.38558741, 5.51381568, 5.64204395,
       5.77027222, 5.89850049, 6.02672876, 6.15495704, 6.28318531])

In [36]:
f = np.sin(x)
f

array([ 0.00000000e+00,  1.27877162e-01,  2.53654584e-01,  3.75267005e-01,
        4.90717552e-01,  5.98110530e-01,  6.95682551e-01,  7.81831482e-01,
        8.55142763e-01,  9.14412623e-01,  9.58667853e-01,  9.87181783e-01,
        9.99486216e-01,  9.95379113e-01,  9.74927912e-01,  9.38468422e-01,
        8.86599306e-01,  8.20172255e-01,  7.40277997e-01,  6.48228395e-01,
        5.45534901e-01,  4.33883739e-01,  3.15108218e-01,  1.91158629e-01,
        6.40702200e-02, -6.40702200e-02, -1.91158629e-01, -3.15108218e-01,
       -4.33883739e-01, -5.45534901e-01, -6.48228395e-01, -7.40277997e-01,
       -8.20172255e-01, -8.86599306e-01, -9.38468422e-01, -9.74927912e-01,
       -9.95379113e-01, -9.99486216e-01, -9.87181783e-01, -9.58667853e-01,
       -9.14412623e-01, -8.55142763e-01, -7.81831482e-01, -6.95682551e-01,
       -5.98110530e-01, -4.90717552e-01, -3.75267005e-01, -2.53654584e-01,
       -1.27877162e-01, -2.44929360e-16])

### Printing Arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right
- the second-to-last is printed from top to bottom
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line

1-dimensional arrays are then printed as rows, 2-dimensional arrays as matrices, and 3-dimensional arrays as lists of matrices.

In [37]:
a = np.arange(6) # 1d array
print(a)
a

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

In [38]:
b = np.arange(12).reshape(4, 3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
c = np.arange(24).reshape(2, 3, 4) # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


We'll talk more about `reshape` later.

If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [40]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [41]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behavior and force NumPy to print the entire array, you can change the printing options using `set_printoptions`.

In [72]:
import sys # sys module should be imported
np.set_printoptions(threshold=sys.maxsize)

In [ ]:
print(np.arange(10000).reshape(100, 100))

### Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [183]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [184]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [185]:
c = a + b
c

array([20, 31, 42, 53])

In [47]:
b**2

array([0, 1, 4, 9])

In [48]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [49]:
a < 35

array([ True,  True, False, False])

Unlike in other matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator or the `dot` function/method:

In [186]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [187]:
A

array([[1, 1],
       [0, 1]])

In [188]:
B

array([[2, 0],
       [3, 4]])

In [189]:
A * B # elementwise product

array([[2, 0],
       [0, 4]])

Matrix multiplication is an operation that takes two matrices as input and produces a single matrix by multiplying rows of the first matrix to columns of the second matrix. In matrix multiplication, make sure that the number of rows of the first matrix is equal to the number of columns in the second matrix.

Example: multiplication of 2 matrices of size `2x2`

In [51]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [52]:
A.dot(B) # matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as `+=` and `*=`, act in place to modify an existing array rather than create a new one.

In [60]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
a *= 3
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [230]:
rg = np.random.default_rng(1) # create instance of default random number generator
b = rg.random((2,3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [63]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [64]:
a += b
a

array([[6.51182162, 6.9504637 , 6.14415961],
       [6.94864945, 6.31183145, 6.42332645]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as *upcasting*).

In [219]:
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)

In [220]:
a

array([1, 1, 1], dtype=int32)

In [210]:
b

array([0.        , 1.57079633, 3.14159265])

In [211]:
b.dtype.name

'float64'

In [221]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [76]:
c.dtype.name

'float64'

In [224]:
np.exp(1) # equal to constant e

2.718281828459045

In [222]:
f = np.exp(c)
f

array([ 2.71828183, 13.07623325, 62.90292428])

In [77]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [225]:
#help(np.exp)
?np.exp

In [78]:
d.dtype.name

'complex128'

In [226]:
2**c

array([ 2.        ,  5.94137285, 17.64995565])

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the `ndarray` class.

In mathematics, a unary operation is an operation with only one operand, i.e., a single input. Here are some examples:

In [233]:
a = rg.random((2,3))
a

array([[0.20345524, 0.26231334, 0.75036467],
       [0.28040876, 0.48519097, 0.9807372 ]])

In [234]:
a.sum()

2.962470185966965

In [235]:
a.min()

0.20345524067614962

In [236]:
a.max()

0.9807371998012386

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter, you can apply an operation along the specified axis of an array:

In [83]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [85]:
b.min(axis=1) # min of each row

array([0, 4, 8])

In [86]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Universal Functions

NumPy provides familiar mathematical functions such as `sin`, `cos`, and `exp`. In NumPy, these are called "universal functions". Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [87]:
B = np.arange(3)
B

array([0, 1, 2])

In [88]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [89]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [91]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

### Indexing, Slicing, Iterating

1-dimensional arrays can be indexed, sliced, and iterated over, much like lists and other Python sequences.

In [92]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [93]:
a[2]

8

In [94]:
a[2:5]

array([ 8, 27, 64])

In [95]:
a[:6:2] = 1000 # equivalent to a[0:6:2] = 1000
# from start to position 6, exclusive, set every 2nd element to 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [96]:
a[::-1] # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [97]:
for i in a:
    print(i ** (1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [98]:
def f(x,y):
    return 10 * x + y

In [100]:
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [101]:
b[2, 3]

23

In [102]:
b[0:5, 1] # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [103]:
b[:, 1]  # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [104]:
b[1:3, :] # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [105]:
b[-1] # the last row; equivalent to b[-1,:]

array([40, 41, 42, 43])

The expression within brackets in `b[i]` is treated as an `i` followed by as many instaces of `:` needed to represent the remaining axes. NumPy also allows you to write this using dots: `b[i, ...]`.

The dots `(...)` represent as many colons as needed to produce a complete indexing tuple. For example, if `x` is an array with 4 axes, then:

- `x[1, 2, ...]` is equivalent to `x[1, 2, :, :]`
- `x[..., 3]` is equivalent to `x[:, :, :, 3]`
- `x[4, ..., 5]` is equivalent to `x[4, :, :, 5]`

NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements.

In [237]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [238]:
c = np.array([[[0, 1, 2], # a 3d array (two stacked 2d arrays)
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [108]:
c.shape

(2, 2, 3)

In [109]:
c[1, ...] # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [110]:
c[..., 2] # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [239]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [113]:
for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [240]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [241]:
for x in b:
    print(x)

[0.51182162 0.9504637  0.14415961]
[0.94864945 0.31183145 0.42332645]


However, if you want to perform an operation on each element in the array, you can use the `flat` attribute, which is an iterator over all the elements of the array:

In [242]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [119]:
for element in c.flat:
    print(element)

0
1
2
10
12
13
100
101
102
110
112
113


In [243]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [244]:
for x in b.flat:
    print(x)

0.5118216247002567
0.9504636963259353
0.14415961271963373
0.9486494471372439
0.31183145201048545
0.42332644897257565


### Shape Manipulation

#### What is the `shape` of an Array?

The `shape` of an array is a tuple that gives you an indication of the number of dimensions in the array.

An array has a `shape` given by the number of elements along each axis:

In [248]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[0., 5., 4., 0.],
       [6., 8., 5., 2.],
       [8., 5., 5., 7.]])

In [116]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following 3 commands all return a modified array, but do not change the original array:

In [249]:
a.ravel() # returns the array flattened

array([0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.])

In [250]:
a.reshape(6, 2) # returns the array with a modified shape

array([[0., 5.],
       [4., 0.],
       [6., 8.],
       [5., 2.],
       [8., 5.],
       [5., 7.]])

In [251]:
a

array([[0., 5., 4., 0.],
       [6., 8., 5., 2.],
       [8., 5., 5., 7.]])

In [252]:
a.T # returns the array transposed

array([[0., 6., 8.],
       [5., 8., 5.],
       [4., 5., 5.],
       [0., 2., 7.]])

In [121]:
a.T.shape

(4, 3)

In [122]:
a.shape

(3, 4)

The order of the elements in the array resulting from `ravel` is based on the rightmost index changing the fastest, so the element after `a[0, 0]` is `a[0, 1]`. If the array is reshaped to some other shape, it is treated the same way. The functions `ravel` and `reshape` also have an optional argument that would instruct them to order the elements based on the leftmost index changing the fastest.

The `reshape` function returns its argument with a modified shape, whereas the `ndarray.resize` method modifies the array itself:

In [123]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [125]:
a.resize((2, 6))
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

If a dimension is given as `-1` in a reshaping operation, the other dimensions are automatically calculated:

In [126]:
a.reshape(3, -1) # a.reshape(3, 4)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

### Stacking Together Different Arrays

Several arrays can be stacked together along different axes:

In [127]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[9., 7.],
       [5., 2.]])

In [128]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[1., 9.],
       [5., 1.]])

In [129]:
np.vstack((a, b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [130]:
np.hstack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

The function `column_stack` stacks 1-dimensional arrays as columns into a 2-dimensional array. It is only equivalent to `hstack` for 2-dimensional arrays:

In [131]:
np.column_stack((a, b)) # with 2d arrays

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [132]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b)) # returns a 2d array

array([[4., 3.],
       [2., 8.]])

In [133]:
np.hstack((a, b)) # the result is different

array([4., 2., 3., 8.])

In [134]:
from numpy import newaxis
a[:, newaxis] # view a as a 2d column vector

array([[4.],
       [2.]])

In [135]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [136]:
np.hstack((a[:,newaxis],b[:,newaxis])) # the result is the same

array([[4., 3.],
       [2., 8.]])

On the other hand, the function `row_stack` is equivalent to `vstack` for any input array. In fact, `row_stack` is an alias for `vstack`:

In [137]:
np.column_stack is np.hstack

False

In [138]:
np.row_stack is np.vstack

True

In general, for arrays with more than 2 dimensions, `hstack` stacks along their second axes, `vstack` stacks along their first axes, and `concatenate` allows for an optional argument giving the number of the axis along which the concatenation should happen.

In complex cases `r_` and `c_` are useful for creating arrays by stacking numbers along 1 axis. They allow the use of range literals (`:`):

In [139]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

When used with arrays as argument `r_` and `c_` are similar to `vstack` and `hstack` in their default behavior, but allow for an optional argument giving the number of the axis on which to concatenate.

### Splitting One Array into Several Small Ones

Using `hsplit`, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [257]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[1., 8., 6., 7., 1., 8., 1., 0., 8., 8., 8., 4.],
       [2., 0., 6., 7., 8., 2., 2., 6., 8., 9., 1., 4.]])

In [259]:
np.hsplit(a, 3) # split a into 3

[array([[1., 8., 6., 7.],
        [2., 0., 6., 7.]]),
 array([[1., 8., 1., 0.],
        [8., 2., 2., 6.]]),
 array([[8., 8., 8., 4.],
        [8., 9., 1., 4.]])]

In [263]:
np.hsplit(a, (3, 4)) # split a after the third and fourth columns

[array([[1., 8., 6.],
        [2., 0., 6.]]),
 array([[7.],
        [7.]]),
 array([[1., 8., 1., 0., 8., 8., 8., 4.],
        [8., 2., 2., 6., 8., 9., 1., 4.]])]

`vsplit` splits along the vertical axis, and `array_split` allows you to specify along which axis to split.

### Copies and Views

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are 3 cases:

#### No Copy At All

Simple assignments make no copy of objects or their data.

In [265]:
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
b = a # no new object is created
b is a # a and b are two names for the same ndarray object

True

Python passes mutable objects as references, so function calls make no copy:

In [144]:
def f(x):
    print(id(x)) # id is a unique identifier of an object
    
f(a)

140568677605072


In [145]:
id(a)

140568677605072

#### View or Shallow Copy

Different array objects can share the same data. The `view` method creates a new array object that looks at the same data.

In [266]:
c = a.view()
c is a

False

In [147]:
c.base is a # c is a view of the data owned by a

True

In [268]:
c = c.reshape((2, 6)) # a's shape doesn't change
a.shape

(3, 4)

In [270]:
c[0, 4] = 1234 # a's data changes
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [272]:
c.reshape((3, 4))

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [271]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:

In [167]:
s = a[:, 1:3]
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [168]:
s[:] = 10 # s[:] is a view of s, equivalent to s[:, :]
# note the difference between s = 10 and s[:] = 10
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [169]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Deep Copy

The `copy` method makes a complete copy of the array and its data:

In [170]:
d = a.copy() # a new array object with new data is created
d is a

False

In [171]:
d

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [172]:
d.base is a # d doesn't share anything with a

False

In [173]:
d[0, 0] = 9999
d

array([[9999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [273]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Sometimes copy should be called after slicing if the original array is not required anymore. For example, suppose `a` is a huge intermediate result, and the final result `b` only contains a small fraction of `a`. A deep copy should be made when constructing `b` with slicing:

In [174]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a # the memory of a can be released
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [175]:
a

NameError: name 'a' is not defined

If `b = a[:100]` is used instead, `a` is referenced by `b`, and will persist in memory even if `del a` is executed.