## NumPy Basics

NumPy's main object is the homogeneous multi-dimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy, dimensions are called axes.

For example, the coordinates of a point in a 3-dimensional space `[1, 2, 1]` has one axis. That axis has 3 elements in it, so we say it has a length of 3. 

NumPy's array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the standard Python library class `array.array`, which only handles 1-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

- `ndarray.ndim`: the number of axes (dimensions) of the array
- `ndarray.shape`: the dimensions of the array
    - This is a tuple of integers indicating the size of the array in each dimension. For a matrix with `n` rows and `m` columns, the `shape` will be `(n, m)`. The length of the `shape` tuple is therefore the number of axes, `ndim`  
- `ndarray.size`: the total number of elements of the array
    - This is equal to the product of the elements of the `shape`, `n x m`
- `ndarray.dtype`: an object describing the type of elements in the array
    - One can create or specify `dtype`s using standard Python types. Additionally, NumPy provides types of its own, e.g., `numpy.int32`, `numpy.int16`, `numpy.float64`

### Example

In [68]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype

dtype('int64')

In [5]:
a.size

15

In [6]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.ndim

1

In [11]:
b.shape

(3,)

### Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [12]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [71]:
b = np.array([1.2, 3.5, 5.1, 6])
b.dtype

dtype('float64')

In [70]:
print(b)

[1.2 3.5 5.1 6. ]


A frequent error consists in calling an array with multiple arguments rather than providing a single sequence as an argument.

In [15]:
a = np.array(1,2,3,4) # wrong

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [17]:
a = np.array([1, 2, 3, 4]) # right
a

array([1, 2, 3, 4])

`array` transforms sequences of sequences into 2-dimensional arrays, sequences of sequences of sequences into 3-dimensional arrays, and so on.

In [18]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [19]:
b.dtype

dtype('float64')

In [20]:
b.ndim

2

The type of the array can also be explicitly specified at creation time:

In [21]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the `dtype` of the created array is `float64`.

In [22]:
c = np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
c.dtype

dtype('float64')

In [25]:
d = np.ones((2,3,4), dtype=np.int16) # dtype can also be specified
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
d.ndim

3

In [30]:
np.empty((2,3), dtype=np.float16) # uninitialized

array([[ 0.000e+00,  0.000e+00,  0.000e+00],
       [-7.812e-03, -7.236e-01, -2.158e-04]], dtype=float16)

To create sequences of numbers, NumPy provides the `arange` function, which is analogous to the Python built-in `range`, but returns an array.

In [31]:
e = np.arange(10, 40, 5) # analogous to range(10, 40, 5)
e

array([10, 15, 20, 25, 30, 35])

In [32]:
np.arange(0, 3, 0.3) # accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want, instead of the step:

In [33]:
np.linspace(0, 2, 9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [35]:
from numpy import pi
x = np.linspace(0, 2*pi, 50) # useful to evaluate function at lots of points
x

array([0.        , 0.12822827, 0.25645654, 0.38468481, 0.51291309,
       0.64114136, 0.76936963, 0.8975979 , 1.02582617, 1.15405444,
       1.28228272, 1.41051099, 1.53873926, 1.66696753, 1.7951958 ,
       1.92342407, 2.05165235, 2.17988062, 2.30810889, 2.43633716,
       2.56456543, 2.6927937 , 2.82102197, 2.94925025, 3.07747852,
       3.20570679, 3.33393506, 3.46216333, 3.5903916 , 3.71861988,
       3.84684815, 3.97507642, 4.10330469, 4.23153296, 4.35976123,
       4.48798951, 4.61621778, 4.74444605, 4.87267432, 5.00090259,
       5.12913086, 5.25735913, 5.38558741, 5.51381568, 5.64204395,
       5.77027222, 5.89850049, 6.02672876, 6.15495704, 6.28318531])

In [36]:
f = np.sin(x)
f

array([ 0.00000000e+00,  1.27877162e-01,  2.53654584e-01,  3.75267005e-01,
        4.90717552e-01,  5.98110530e-01,  6.95682551e-01,  7.81831482e-01,
        8.55142763e-01,  9.14412623e-01,  9.58667853e-01,  9.87181783e-01,
        9.99486216e-01,  9.95379113e-01,  9.74927912e-01,  9.38468422e-01,
        8.86599306e-01,  8.20172255e-01,  7.40277997e-01,  6.48228395e-01,
        5.45534901e-01,  4.33883739e-01,  3.15108218e-01,  1.91158629e-01,
        6.40702200e-02, -6.40702200e-02, -1.91158629e-01, -3.15108218e-01,
       -4.33883739e-01, -5.45534901e-01, -6.48228395e-01, -7.40277997e-01,
       -8.20172255e-01, -8.86599306e-01, -9.38468422e-01, -9.74927912e-01,
       -9.95379113e-01, -9.99486216e-01, -9.87181783e-01, -9.58667853e-01,
       -9.14412623e-01, -8.55142763e-01, -7.81831482e-01, -6.95682551e-01,
       -5.98110530e-01, -4.90717552e-01, -3.75267005e-01, -2.53654584e-01,
       -1.27877162e-01, -2.44929360e-16])

### Printing Arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right
- the second-to-last is printed from top to bottom
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line

1-dimensional arrays are then printed as rows, 2-dimensional arrays as matrices, and 3-dimensional arrays as lists of matrices.

In [37]:
a = np.arange(6) # 1d array
print(a)
a

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

In [38]:
b = np.arange(12).reshape(4, 3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [39]:
c = np.arange(24).reshape(2, 3, 4) # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


We'll talk more about `reshape` later.

If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [40]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [41]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behavior and force NumPy to print the entire array, you can change the printing options using `set_printoptions`.

In [72]:
import sys # sys module should be imported
np.set_printoptions(threshold=sys.maxsize)

In [ ]:
print(np.arange(10000).reshape(100, 100))

### Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [44]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [45]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [46]:
c = a - b
c

array([20, 29, 38, 47])

In [47]:
b**2

array([0, 1, 4, 9])

In [48]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [49]:
a < 35

array([ True,  True, False, False])

Unlike in other matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator or the `dot` function/method:

In [50]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
A * B # elementwise product

array([[2, 0],
       [0, 4]])

Matrix multiplication is an operation that takes two matrices as input and produces a single matrix by multiplying rows of the first matrix to columns of the second matrix. In matrix multiplication, make sure that the number of rows of the first matrix is equal to the number of columns in the second matrix.

Example: multiplication of 2 matrices of size `2x2`

In [51]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [52]:
A.dot(B) # matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as `+=` and `*=`, act in place to modify an existing array rather than create a new one.

In [60]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
a *= 3
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [62]:
rg = np.random.default_rng(1) # create instance of default random number generator
b = rg.random((2,3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [63]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [64]:
a += b # b is not automatically converted to integer type
a

array([[6.51182162, 6.9504637 , 6.14415961],
       [6.94864945, 6.31183145, 6.42332645]])